name: Angular-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages  # Branch where the site will be deployed
          build_dir: dist/app-wiki-anime         # Directory to deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
